# evervim
[[plugins]]
repo = 'kakkyz81/evervim'
hook_add ='''
nnoremap <Leader>l :EvervimNotebookList<CR>
nnoremap <Leader>s :EvervimSearchByQuery<Space>
nnoremap <Leader>c :EvervimCreateNote<CR>
onoremap <Leader>t :EvervimListTags<CR>
let g:evervim_devtoken=readfile($HOME . '/_evernoteToken')[1]
'''
