
#lightline
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    if has('win32')
        "windows
        source ~/vimfiles/rc/plugins/lightline.rc.vim
    else
        source ~/.vim/rc/plugins/lightline.rc.vim
    endif
'''
