
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = "has('lua')"
on_event = 'InsertEnter'
hook_add = '''
  let g:neocomplete#enable_at_startup = 1
  source ~/.vim/rc/plugins/neocomplete.rc.vim
'''

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = '''
  let g:jedi#use_tabs_not_buffers = 1
  let g:jedi#popup_select_first = 0
  let g:jedi#popup_on_dot = 0
  autocmd FileType python setlocal completeopt-=preview
'''
