#evervim
[[plugins]]
repo = 'kakkyz81/evervim'
hook_add ='''
nnoremap <Leader>l :EvervimNotebookList<CR>
nnoremap <Leader>s :EvervimSearchByQuery<Space>
nnoremap <Leader>c :EvervimCreateNote<CR>
nnoremap <Leader>t :EvervimListTags<CR>
let g:evervim_devtoken=readfile(g:DIR . '/_evernoteToken')[1]
'''

#lightline
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    if has('win32')
        "windows
        source ~/vimfiles/rc/plugins/lightline.rc.vim
    else
        source ~/.vim/rc/plugins/lightline.rc.vim
    endif
'''


#tpope/vim-unimpaired
[[plugins]]
repo = 'tpope/vim-unimpaired'

# Prettyprint vim variables.
[[plugins]]
repo = 'thinca/vim-prettyprint'

