syntax on        "シンタックスハイライト
set noautoindent   "改行した後の行のインデントの深さを、前の行と同じに
set expandtab    "タブで挿入する文字をスペースに
set tabstop=4    "タブの幅を指定します。
set shiftwidth=4 "自動インデントの幅を指定します
set cursorline   "カーソルのある行にアンダーラインを引きます。
set number       "行番号を表示します。
"set statusline=%F%r%h%= "ステータスラインに表示
set whichwrap=b,s,[,],<,>,~ "行の先頭や終わりでの移動
set backspace=start,eol,indent "バックスペースで削除、改行、先頭移動
